site_name: WiCyS 2022 CTF
site_url: https://wictf.com
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - index.md
  - rules.md
  - registration.md
  - gameboard.md
  - support.md
  - FAQ: 'faq.md'
  - materials.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  logo: assets/flag.png      
  favicon: assets/flag.png
edit_uri: ""
copyright: Copyright &copy; 2022 Carnegie Mellon University
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sei_cmu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/software-engineering-institute/
    - icon: fontawesome/brands/github
      link: https://github.com/cmu-sei
