site_name: WiCyS 2022 CTF
site_url: https://dev.wictf.com
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - index.md
  - rules.md
  - registration.md
  - gameboard.md
  - support.md
  - faq.md
  - materials.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  logo: assets/flag.png      
  favicon: assets/flag.svg
  features:
    - navigation.tabs
edit_uri: ""
copyright: Copyright &copy; 2022 Carnegie Mellon University
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmu-sei
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/cmusei
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sei_cmu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/software-engineering-institute/

